### PR TITLE
Version 2.0

### PR DESCRIPTION
**Pull request by ayushsingh12march**
I have taken Footer component from App.js and added individually at the end to all the components.
Reason :- To avoid the media links(redundent) in footer for the About us page

### CODE REVIEW

**Comment by Arav1nd2** [comment]
Good Work da, 
There are some issues with your code.
1. Whatever you did to the footers, the alignment of the social links is affected, ( Earlier it was like half inside the footer and half outside of it )
2. I think a better solution for redundant footer would be to use a if else check in the footer component to check whether social media links are required ( Although there are some security vulns we need to be careful of )
3. There seems to be lesser white space in the component when compared to the design. Try to add some padding.
4. Also there are some alignment issues in high resolution desktops. I'll add a picture to show you the differences
Screenshot from 2020-06-10 17-07-19
5. Add small animations to the button hover effects and remove border and outline for the buttons


Cheers!

**Comment by Arav1nd2** [comment]
Also One major Issue, Deepak's twitter feed is not working after your changes, it simply shows a link called tweets by DSC SASTRA

**Comment by ayushsingh12march** [comment]
On it👍 , I used if else only for the footer,  I dont understand how it affected the alignment. Others I can see. 
For now I am leaving footer how it was. Maybe later you change it, bcz I dont understand why my if else is affecting the alignment of the links

**Comment by ayushsingh12march** [comment]
1) I have added small animation for Contact Us button
2) Removed borders from media buttons.
3) Left Footer unchanged as of now
4) Added some padding as well.

Still unclear about :-
1) Which resolution is affecting the spacings 
2) Avoiding media buttons in Footer component 
3) Where the Contact Us button should link to.

Kindly merge if the issues are minimum. So that Deepak can pick up the boiler plate and start working.

**Comment by Ram-the-coder** [comment]
> 4. Also there are some alignment issues in high resolution desktops. I'll add a picture to show you the differences

I wonder if its a problem with whatever browser you are using @Arav1nd2 🤔

**Comment by Arav1nd2** [comment]
Could be, but I am using Chrome only

**Comment by ayushsingh12march** [comment]
Actually the images and text are moving apart in higher resolutions. I checked in Chrome and Firefox.
Now I am not sure which browsers are not supporting the flex property. Any ideas?

**Pull request merged**
