### PR TITLE
Added social media buttons, put footer in app.js and fixed scrollbar

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Ram-the-coder** [comment]
1. Whatever you did to remove the scroll bar has brought in some issues. The laptop view looks ok. But as we make the screen size smaller, a lot of alignment issues are coming and there is some space in the right size. The navbar is no longer sticky. Too much space between two sections in the home page.
2. The twitter embed would look better with a box shadow

**Comment by Arav1nd2** [comment]
The code seems fine, 
1) Since you have implemented the responsive logic in JS rather than using media queries, they will change when the screen width changes. But that is fine for now, we can check that later.
2) But as far as the twitter feed, in mobile devices, the contact form in the background is disturbing  the view, So add an overlay to the popup, so that the background gets blurred when the twitter feed is opened

**Comment by Arav1nd2** [comment]
3. Also when clicking on the social links, make sure it opens in a new tab

**Comment by ghost** [comment]
Is it good now?

**Comment by Arav1nd2** [comment]
Perfect!

**Review by Arav1nd2 — APPROVED** [review]

**Pull request merged**
