### PR TITLE
refactor: event cards

### PR DESCRIPTION
**Pull request by Ram-the-coder**
1. Truncate the event description displayed. 2. Make event card clickable - on click open event modal. Todo: Show the full description in event modal.

### CODE REVIEW

**Comment by Ram-the-coder** [comment]
Made event modal responsive.
The modal now also shows the full description of the event.

**Comment by Arav1nd2** [comment]
#11 
Modal seems responsive now, but the close button's position is changing according to the screen sizes.

I suggest better remove the button. Modal closes when clicked anywhere outside it.
If possible add key bindings for 'Esc' key so that it gets closed when pressing Esc key

**Comment by Ram-the-coder** [comment]
@Arav1nd2 I changed the way some stuff was styled... Now check if the problem with the close button is still there.

**Comment by Arav1nd2** [comment]
Now, the button looks proper in all screens! 🎉

**Pull request merged**
